# Generated by Django 3.1.7 on 2021-07-06 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dayofflight',
            old_name='departure_date',
            new_name='date',
        ),
    ]
