# Generated by Django 3.1.7 on 2021-10-03 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_airlinebooking_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='seat_number',
            field=models.IntegerField(default=1),
        ),
    ]
